// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooSystem.Infrastructure.DataAcess;

#nullable disable

namespace ZooSystem.Migrations
{
    [DbContext(typeof(ZooSystemDbContext))]
    partial class ZooSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooSystem.Domain.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95bf54a5-f2d7-4d9f-a858-b1eb8a3731f2"),
                            DataNascimento = new DateTime(2015, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Leão africano",
                            Especie = "Panthera leo",
                            Habitat = "Savana",
                            Nome = "Leão",
                            PaisOrigem = "África do Sul"
                        },
                        new
                        {
                            Id = new Guid("94620ad4-a804-4489-9fb5-bda950ddfaff"),
                            DataNascimento = new DateTime(2017, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Girafa macho adulto",
                            Especie = "Giraffa camelopardalis",
                            Habitat = "Savana",
                            Nome = "Girafa",
                            PaisOrigem = "Quênia"
                        });
                });

            modelBuilder.Entity("ZooSystem.Domain.Entities.AnimalCuidado", b =>
                {
                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuidadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimalId", "CuidadoId");

                    b.HasIndex("CuidadoId");

                    b.ToTable("AnimaisCuidados");
                });

            modelBuilder.Entity("ZooSystem.Domain.Entities.Cuidado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cuidados");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6221bd98-d3a6-4a56-b98a-46613606c964"),
                            Descricao = "Fornecimento de alimento",
                            Frequencia = "Diária",
                            Nome = "Alimentação"
                        },
                        new
                        {
                            Id = new Guid("1a5349ad-5240-4c7f-a9b7-e497bcb99aac"),
                            Descricao = "Aplicação de vacinas",
                            Frequencia = "Anual",
                            Nome = "Vacinação"
                        });
                });

            modelBuilder.Entity("ZooSystem.Domain.Entities.AnimalCuidado", b =>
                {
                    b.HasOne("ZooSystem.Domain.Entities.Animal", "Animal")
                        .WithMany("AnimaisCuidados")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooSystem.Domain.Entities.Cuidado", "Cuidado")
                        .WithMany("AnimaisCuidados")
                        .HasForeignKey("CuidadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cuidado");
                });

            modelBuilder.Entity("ZooSystem.Domain.Entities.Animal", b =>
                {
                    b.Navigation("AnimaisCuidados");
                });

            modelBuilder.Entity("ZooSystem.Domain.Entities.Cuidado", b =>
                {
                    b.Navigation("AnimaisCuidados");
                });
#pragma warning restore 612, 618
        }
    }
}
